spring:
  application:
    name: test
  config:
    import: 'optional:configserver:'
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
#      retry:
#      request-read-timeout
#      request-connect-timeout
    bus:
      trace:
        enabled: true

management:
  endpoints:
    web:
      base-path: "/admin"
      exposure:
        include: '*'
  endpoint:
    env:
      post:
        enabled: true